name: AWS S3 List with OIDC Auth

on:
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-1 

permissions:
      id-token: write   # Required for OIDC authentication
      contents: read  

jobs:
  ListS3Buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::160475665286:role/GitHubAction-AssumeRoleWithAction 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity

      - name: List S3 Buckets
        run: |
          aws s3 ls
