name: AWS S3 List with OIDC Auth

on:
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-1  # Change to reflect your Region

permissions:
      id-token: write   # Required for OIDC authentication
      contents: read    # Required for actions/checkout

jobs:
  ListS3Buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Debug Token Claims
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}

      - name: Debug GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository owner: ${{ github.repository_owner }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::160475665286:role/GitHubAction-AssumeRoleWithAction 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity

      - name: List S3 Buckets
        run: |
          aws s3 ls
          # For specific bucket:
          # aws s3 ls s3://your-bucket-name/
          # For recursive listing:
          # aws s3 ls s3://your-bucket-name/ --recursive
